### ISSUE TITLE
Automatically enter mining mode while maintaining mouse move mode

### ISSUE THREAD

**Issue by gattigcg1** [rampaa/JL#100]
So I prefer mouse over mode, but I also would like mining mode to be activated automatically to save a button click. If I put it as "mouse click/touch" then its already in mouse over mode but then you gotta click which I prefer mouse over mode over that.

**Comment by rampaa** [comment]
I'd imagine "Mouse move" mode + auto enabled mining mode would be pretty annoying to use. Notice that when you activate the mining mode when you use "Mouse move" mode, you can't hover over other terms in the main window before closing the popup itself. So every time you accidentally and/or inevitably (e.g. when you have say, 3 lines of text and the term you want to look up is in the second line) hover over the wrong character, you'd need to close the opened popup to be able to look up the correct character. If you truly need to mine every word you look up, then just use the "Mouse click/Touch" mode, "Mouse move" mode + auto enabled mining mode would be just way less ergonomic to use. If you don't need to mine every single term you look up though, "Mouse move" mode + middle mouse click when you need to enable the mining mode would be more ergonomic to use.
