### ISSUE TITLE
request: configurable line height

### ISSUE THREAD

**Issue by FenTheFox** [rampaa/JL#101]
my preference, when possible (ie, mostly in adv games), is to have jl over the text of the vn i'm reading. matching font size and height is usually not an issue, but quite often jl has more space between lines than the vn and so while the first line will be matched up perfectly subsequent lines will not

**Comment by rampaa** [comment]
AFAIK, it's currently not possible to change the line height of a TextBox in WPF, I've opened an issue for it at https://github.com/dotnet/wpf/issues/9867. (I've also opened an issue for kerning while I am at it, see https://github.com/dotnet/wpf/issues/9868). I will not be able to provide this option until WPF itself provides it.

Regardless, I highly suggest you to enable the following options if you didn't already:
* Preferences->Main Window->Text only visible on unhover
* Preferences->Main Window->Change opacity on unhover
* Preferences->Main Window->Hide all buttons when mouse is not over the title bar

Making JL only visible when it's hovered will be way easier than trying to perfectly align JL's main window with a game text box, not to mention it should be even more immersive if you don't see JL at all when you don't need it.
