### ISSUE TITLE
A way to edit the text fed to JL after its sent

### ISSUE THREAD

**Issue by gattigcg1** [rampaa/JL#105]
If someone's using an OCR, and the result is wrong, and you want to edit the text in JL itself before sending it to Anki. Or if the formatting of the input is not to someone's liking, I feel like an option to edit it, would be nice. I know there's a way to add custom regex but that can't do things like fix incorrect OCR-ing.

**Comment by rampaa** [comment]
You can disable `Preferences->Main Window->Read only` to make the main window editable. You can disable that option permanently or you can use the hotkey you see under`Preferences->Hotkeys->Toggle read only option` to toggle it on the fly.

**Comment by gattigcg1** [comment]
Seems like I can add spaces and text but I can't edit existing text

**Comment by rampaa** [comment]
I'm not sure what you mean by that. You can manipulate the text just like in any other text editor. You can delete the text with the backspace key.
