### ISSUE TITLE
If clipboard text is the same, do not send

### ISSUE THREAD

**Issue by gattigcg1** [rampaa/JL#108]
Using AutoOCR feature in Kamui it's often the case that the exact same line gets picked up by the OCR over and over and the text in JL gets hard to read because the definition flashes in and out when it's the exact same text that gets sent. Is there some setting to prevent JL from accepting new clipboard events when it's the exact same text? I also have a separate script that relies on clipboard timing so if it's the exact same text, i'd prefer to only capture the first event of that to prevent issues. This is via clipboard copying by the way, kamui doesn't have websockets yet.

**Comment by rampaa** [comment]
* Enable `Preferences -> Main Window -> Merge sequential texts when they match`
* Set the value of `Preferences -> Main Window -> Max delay between copies to merge sequential texts when they match (in milliseconds)` to 0 to remove the time constraint, or set it to a resonable number
* Disable `Preferences -> Main Window -> Hide popups on text change`

I might add a new option for users who do not wish to merge mathing sequential texts in general but still want to discard duplicate text in the next version of JL.
