### ISSUE TITLE
Better ordering of results

### ISSUE THREAD

**Issue by mertvn** [rampaa/JL#13]
Currently, we sort results mainly by their frequency. This causes some words to have the wrong readings displayed in the first spot. 
E.g.: 姉's first result should be あね, not ねえ

**Comment by rampaa** [comment]
I am quite happy with the [current ordering algorithm](https://github.com/rampaa/JL/blob/3afa620a4f6428305a5a8ea99c3b39ef1b833059/JL.Core/Lookup/LookupUtils.cs#L295). ねえ can appear before あね if the frequency dictionary used indicates ねえ is more frequent. But that's not something JL should "correct" manually.
