### ISSUE TITLE
after 1.6 update not catching every line from clipboard

### ISSUE THREAD

**Issue by yourmom2002** [rampaa/JL#15]
So yeah, after 1.6, sometimes JL won't get line from clipboard. Happens maybe 1-2 times per 10 lines, works fine if i manually copy line one more time. 
Fixed as soon as i downgraded back to 1.5

**Comment by rampaa** [comment]
Probably caused by efe21bbcd46047fe764b3c48473e7ec7af8137e9. JL now discards clipboard changes that happen within 5 ms in order to work around the aforementioned bug.

Did this happen when you were leisurely reading? If that's the case, I will have to revert the change.

**Comment by yourmom2002** [comment]
I totaly didn't hold CTRL when this happened, and i shouldn't be THAT fast to break 5 ms / line limit, Just checked, doesn't happen when i go really slow tho. I can do more testing tomorrow, or maybe you can add checkbox for this workaround.

**Comment by rampaa** [comment]
It turns out I made a mistake while calculating the elapsed time. Can you try out v1.7 to see if the issue persists?

**Comment by yourmom2002** [comment]
Yep, i can confirm, issue is gone in 1.7 update. 
Thanks for quick fix.
