### ISSUE TITLE
Possible malware?

### ISSUE THREAD

**Issue by anavels** [rampaa/JL#20]
https://www.reddit.com/r/visualnovels/comments/uq5lv2/reading_visual_novels_in_japanese_help_discussion/i9mwno1?utm_medium=android_app&utm_source=share&context=3

I am not the commentor but as I I have skill to prove or disprove it, is there something for you to say?

**Comment by mertvn** [comment]
False-positive and user-error.
![image](https://user-images.githubusercontent.com/78761720/169848823-f82f1b5e-69cf-4a39-aa23-bef1a5766677.png)
