### ISSUE TITLE
Crashing When Adding/Removing Frequencies

### ISSUE THREAD

**Issue by SaltSouls** [rampaa/JL#24]
Whenever I try to add/remove a frequency it causes the program to crash. Not sure why this is happening as I don't run into this issue with the dictionaries.
Log:
[log20221123.txt](https://github.com/rampaa/JL/files/10076551/log20221123.txt)
Frequency I'm trying to add:
[[Freq] Novels.zip](https://github.com/rampaa/JL/files/10076555/Freq.Novels.zip)

**Comment by rampaa** [comment]
I can import the frequency dictionary you have shared without getting any errors.

Just to be sure:
1) Are you using the latest version of JL?
2) You tried to add it like the following, right?
  Manage frequencies -> Add frequency
  Freq Type: Yomichan
  Path: The path of the folder containing the _unzipped_ content of the zip

Can you share your freqs.json with me? And can you retry adding a frequency dictionary after deleting freqs.json and restarting JL?

**Comment by SaltSouls** [comment]
I tried all of the above and just downloaded it today, so unless there is a version no listed, then I should have the latest one.
Since I recently already reset my freqs.json files, I feel like it won't properly reflect, but here it is:
[freqs.zip](https://github.com/rampaa/JL/files/10076756/freqs.zip)

**Comment by rampaa** [comment]
It should be fixed in [1.15.3](https://github.com/rampaa/JL/releases/tag/1.15.3).
