### ISSUE TITLE
Autohide Popup

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#27]
would be nice if the popup would hide after x amount of ms if the mouse isn´t hovered over it.

**Comment by rampaa** [comment]
How would you expect such a feature to behave when multiple popups are visible?

**Comment by AsuraAce** [comment]
popup should disappear/hide based on the outermost popup. if i´m not mistaken, the behavior i want is the same as the (mouse move) option behavior. only differences are:

- i would be able to control the popup (i have to left click on a word for the popup to appear).
- popup will be in mining mode without me having to click another or a different button.
- don´t have to change anything if i decide to use my touch-screen instead of the mouse

**Comment by AsuraAce** [comment]
an alternative way could be, to simply close the popup whenever someone clicks outside of it, should have the same desired effect.

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/1631fb1553371f5c5672d0270124366c7b894a4f, will be included in the next release.
