### ISSUE TITLE
Add (Tag) VisualStyle for Dictionary and Frequency information

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#28]
would be nice if we could apply visual style (like a tag) to some of the information represented in the popup dictionaries like in the image below.

![image](https://user-images.githubusercontent.com/13394741/214085088-7db0fe5c-bc81-49cb-b8db-bfb2a97c333a.png)

**Comment by rampaa** [comment]
Adding this for dictionary name and frequency results should be trivial. But it's not currently really possible to apply this visual style to other parts of definition (e.g. PoS). This would be possible if JL were to use RichTextBox. But that requires a considerable effort and the end result might make JL slower and/or cause memory leaks.

**Comment by AsuraAce** [comment]
aight, dictionary and frequency tags should help visually.

**Comment by rampaa** [comment]
![MzV2mRrj9S](https://user-images.githubusercontent.com/25622653/215261435-66c8d48b-6996-42ab-9b29-a23374735fd5.png)

This is basically how it would look (you can change the background and text color). If you think this is an improvement, I will implement this later on.

**Comment by AsuraAce** [comment]
- i think they need a little bit of padding and maybe/probably rounded corners
- frequency tags should be separated as well instead of shown as one

**Comment by rampaa** [comment]
> frequency tags should be separated as well instead of shown as one

That would require every frequency dict result to be put into a separate TextBlock, which would worsen JL's performance for little gain.

Adding "Tag" visuals as is probably won't end up in a visually appealing popup, so I will not be implementing it.
