### ISSUE TITLE
Hide Explanatory Message at the top of the popup

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#30]
would like to be able to hide the message that explains how to close the popup and how to mine words.

![image](https://user-images.githubusercontent.com/13394741/214086840-56bb4a40-3b54-47a1-85f0-ba9d60410f96.png)

**Comment by rampaa** [comment]
This is already possible through "Preferences->Popup->Show mining mode reminder" option.

**Comment by AsuraAce** [comment]
thanks missed that option for some reason.
