### ISSUE TITLE
Hide unused dictionary entries in the popup

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#31]
instead of greying-out unused dictionary entries, an option to hide them would be nice.

![image](https://user-images.githubusercontent.com/13394741/214087198-34f21106-b674-44a0-bc5c-c6659a87a1a4.png)

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/b5fef5b1db19431fd4f97218a5f534d7364594b1, will be included in the next release.

**Comment by AsuraAce** [comment]
thanks you very much.
