### ISSUE TITLE
Add - Reset Lifetime & Session Stat Button

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#32]
a dedicated button to reset the above mentioned stats would be nice.

**Comment by rampaa** [comment]
What's the use case for this? Deleting the Stats.json will reset the aforementioned stats, would that not suffice if you plan to nuke your stats every once in a blue moon?

**Comment by AsuraAce** [comment]
want the button so i don´t have to go and delete a json file. **Isn´t necessary**, might as well use the option you mentioned but it is probably more accessible in comparison to deleting a json file. 

Just came to my mind because i wanted to delete my stats, since they aren´t accurate. The time i spend with JL was mostly in relation to setting everything up and getting used to it.

**Comment by rampaa** [comment]
I do agree that adding the aforementioned button would make this more accessible, though I'm not sure if it's a good thing in this case. Accidentally nuking your lifetime stats wouldn't be fun.

Also a pro-tip: If you want to reset some settings, simply deleting the [corresponding setting file](https://github.com/rampaa/JL#where-are-my-settings-stored) will do the trick.

**Comment by AsuraAce** [comment]
you could use a warning popup or even a backup, but as i said it just came to my mind and i can just delete those files every couple of month myself.

another workaround would be to run a texthooker page like anacreondjt in the background.

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/de746d6555f4e230155086dea4b02b703dea58ef, will be included in the next release.
