### ISSUE TITLE
Keep Focus while advancing dialog

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#37]
JL should keep focus even after clicking into a VN to advance the dialog.

- Want to be able keep using hotkeys, more efficient and convenient.
- Adding a hotkey to advance the dialog would probably have the same effect.
- something similar is already possible with (mousewheel) backlog.

**Comment by rampaa** [comment]
I can add an option that would make JL to get keyboard focus on mouse enter. This would let you use hotkeys without clicking on the JL text window. Would that not suffice for your use case?

**Comment by AsuraAce** [comment]
hotkeys on hover should be good enough, thanks.

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/8a9af0a15130118a0ab28d326f5f3d60fdd6306a, will be included in the next release.
