### ISSUE TITLE
Detect Dialog Skip

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#40]
would be nice if JL detects dialog skipping in some form and takes that into consideration for the provided stats.

- playing a different route of a VN can completely mess up stats, which makes them only useful for a short amount of time.

**Comment by rampaa** [comment]
Disable "Enable clipboard text capture" before skipping through Preferences->Main Window or with its hotkey (F12 by default) and re-enable it when you are done skipping.

**Comment by AsuraAce** [comment]
thanks you, will use the hotkey.
