### ISSUE TITLE
Let us choose the browser for lookups with 'S'

### ISSUE THREAD

**Issue by AsuraAce** [rampaa/JL#41]
would be be nice if we could specify the browser in a config file or something instead of using the default browser.

- personally i use different browser for different things. for example: one browser for language learning, another for google services, yet another for web browsing and so on and i have them open in different windows desktop environments as well.
- only have the necessary add-ons in my `language learning browser`

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/548c66c087939a404d207bc5382eb3f26b3e1a2e, will be included in the next release.
