### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by xy2iii** [rampaa/JL#43]
Many textractor based tools have moved from clipboard polling to using a websocket. This method is more reliable and doesn't change your current text when you copy something else.

It may also be faster though I have not tested.

Server examples: 
- https://github.com/sadolit/textractor-websocket
- https://github.com/KamWithK/TextractorSender

Client examples:
- https://github.com/KamWithK/exSTATic
- https://github.com/Renji-XD/texthooker-ui

Would it be possible to consume text from a websocket server?

**Comment by rampaa** [comment]
Implemented in https://github.com/rampaa/JL/commit/1493fce8a49c12078bb471573b92cc5ae1937bf9, will be included in the next release.

**Comment by xy2iii** [comment]
:ikneel:
