### ISSUE TITLE
Path error when adding dictionary

### ISSUE THREAD

**Issue by mylifeishel** [rampaa/JL#44]
I'm using latest version.

error
<img width="479" alt="image" src="https://user-images.githubusercontent.com/20217680/217642188-0aa79c89-7ff5-4d91-89ab-d701b389ef78.png">

folder contents
<img width="109" alt="image" src="https://user-images.githubusercontent.com/20217680/217641940-41b219af-8b6c-4eb9-9770-7135b607dd56.png">

**Comment by mylifeishel** [comment]
I could normally add and use the dictionary with clean extract.
And it crashes when I try to change the path of the dictionary.

 
crash log
[log20230209.txt](https://github.com/rampaa/JL/files/10689786/log20230209.txt)

**Comment by rampaa** [comment]
> <p float="left">
  <img src="https://user-images.githubusercontent.com/20217680/217642188-0aa79c89-7ff5-4d91-89ab-d701b389ef78.png" width="40%" height="40%" />
</p>

This should happen either when the path doesn't exist or when you already use that path for another dictionary. Can you check the dicts.json (located in "...\JL\Config") to see if another dictionary is using the same path? 

> And it crashes when I try to change the path of the dictionary.

When does it crash exactly? Does it crash when you press the "..." button or when you press the "Save" button? Also what OS do you use?

**Comment by mylifeishel** [comment]
> path doesn't exist
Probably because of this. I cant reproduce this error. 
But it still crashes when I click "..." button, save button works normally.
OS is Windows 11

**Comment by rampaa** [comment]
> But it still crashes when I click "..." button, save button works normally.

Just to make sure, you can add dictionaries through "Manage Dictionaries->Add dictionary", right? So you can use the "..." button without a crash while adding dictionaries but it crashes when you try to edit the path of an already added dictionary? Does it also crash if you try to re-select the path in "Add Dictionary" window while adding a dictionary?

**Comment by mylifeishel** [comment]
> So you can use the "..." button without a crash while adding dictionaries but it crashes when you try to edit the path of an already added dictionary

Yes. It crashes editing the path of an exisiting dict. Adding new dicts is normal.

> Does it also crash if you try to re-select the path in "Add Dictionary" window while adding a dictionary?

No

**Comment by rampaa** [comment]
Unfortunately, I cannot reproduce the problem.

But https://github.com/rampaa/JL/commit/fa5c7fba01ac2b87058a85f5801c457f9377c34e might have solved it. The "..." button in "Edit Dictionary" window now acts in the exact same way as it does in "Add Dictionary", so hopefully you it won't crash for you in the next version. Fingers crossed.
