### ISSUE TITLE
Add a soft blinking animation to currently looked up words in text

### ISSUE THREAD

**Issue by ayseru** [rampaa/JL#48]
A clean addition could be that if JL had a blinking animation for the currently looked up word. A soft blinking animation could be an unintrusive way of showing what is currently selected. Similar to how Yomichan look-ups highlight the text, JL could implement something similar to show what part of the text is currently being looked up.

An example of what I'm talking about -
CSS blinking animation example I found from Google:
https://codepen.io/bernheisel/pen/meOQxB
animation duration set to 2s.

**Comment by rampaa** [comment]
> Similar to how Yomichan look-ups highlight the text, JL could implement something similar to show what part of the text is currently being looked up.

There's already Preferences->General->"Highlight the longest match".
