### ISSUE TITLE
Exposing api: Handlebars templating when creating cards

### ISSUE THREAD

**Issue by xy2i** [rampaa/JL#49]
Many basic mining setups involve handlebars in the generated Anki cards. Yomi uses Handlebars internally to generate Anki cards, but allows modifying the template used, creating an API where users can modify the template to generate cards.

This is used in many setups, for example:
- https://github.com/MarvNC/JP-Resources#freq-handlebar looks through the frequency of each definition and averages it, to add a "Frequency" field to anki cards, which is useful when reviewing to get higher frequency cards first.
- https://aquafina-water-bottle.github.io/jp-mining-note/setupyomichan/ does the same with also pitch accent support.

The API for yomichan can be found at https://github.com/themoeway/yomitan/blob/d1c694535113206ba059e83958c1e8c9addd10b2/ext/js/templates/sandbox/anki-template-renderer.js.

Is it possible to add templating support?

**Comment by rampaa** [comment]
See #11
