### ISSUE TITLE
Multiple monitor: Popup only appears on primary screen

### ISSUE THREAD

**Issue by xy2iii** [rampaa/JL#50]
The dictionnary popup seems to only appear on the primary monitor, even if JL is set on the second monitor. This is annoying when playing a vn on multi monitors, as you have to keep switching between the two.

**Comment by rampaa** [comment]
Fixed by https://github.com/rampaa/JL/commit/ee045229a0dee8da5f208102b489dfdf4c427607 (probably, I don't have multiple monitors to test it).
