### ISSUE TITLE
Arm64 release?

### ISSUE THREAD

**Issue by luojunyuan** [rampaa/JL#51]
I build it by myself and run it without anything wrong. (about 800mb memory usage in taskmanager)

Do you willing publish arm version also? Thanks in advance!

**Comment by rampaa** [comment]
Done, see https://github.com/rampaa/JL/commit/3fb78c3159999c09982d7a5211c504a12289b793 and https://github.com/rampaa/JL/commit/083a14ad3ad89ae9e52dd15cb6c40b9110bcb5ef. JL will offer ARM64 releases from now on.
