### ISSUE TITLE
Support additional audio types

### ISSUE THREAD

**Issue by forsakeninfinity** [rampaa/JL#55]
It seems like JL doesn't play some common audio file types so it bugs out with some of the sources from the local audio server. This has become a bigger problem now that the recommended data source has opus audio. You simply get a "Error playing Audio" error if you configure the local audio server as a source with the recommended data source now. FWIW, JL can play the alternative / older mp3 sources but some of the older sources were using `.aac` (in particular, the nhk and shinmeikai8 sources).

The workaround for now is to use the new mp3 sources. But it would be nice if JL could support playing other audio types. A canonical list of the types used by the local audio server are available here: https://github.com/themoeway/local-audio-yomichan/blob/dadd63feb35e89b9030fd18c036d59c45020436b/plugin/server.py#L28

(Logs suggest JL only supports mp3 audio fwiw.
```
System.IO.InvalidDataException: Invalid MP3 file - no MP3 Frames Detected
   at NAudio.Wave.Mp3FileReaderBase..ctor(Stream inputStream, FrameDecompressorBuilder frameDecompressorBuilder, Boolean ownInputStream)
   at JL.Windows.Utilities.WindowsUtils.<>c__DisplayClass56_0.<PlayAudio>b__0() in D:\a\JL\JL\JL.Windows\Utilities\WindowsUtils.cs:line 362
   ```
 )

**Comment by rampaa** [comment]
https://github.com/rampaa/JL/commit/baddea6989ae722a7b1fe723facbebb826d56c25 adds support to additional audio format. JL now can handle .mp3, .aac, .m4a, .ogg, .oga, .flac and probably a few other audio formats.

But JL still does not support the .opus format. See: https://github.com/naudio/NAudio/issues/674.

**Comment by rampaa** [comment]
Adding opus support is not trivial and I don't want to add another huge dependency to add it either. Unless NAudio itself (or a comparable .NET library) adds support for opus format JL will not support it.

Ogg/Vorbis should be pretty comparable to Opus/Vorbis. And I've opened an issue for Ogg/Vorbis support in thelocal audio server repo, see: https://github.com/themoeway/local-audio-yomichan/issues/23. Let's hope they offer an Ogg/Vorbis version as well.

**Comment by rampaa** [comment]
FYI: JL will support the .opus format starting from the next version. See: https://github.com/rampaa/JL/commit/f3b73865db144beb6ab50743bdf86d57c312c6ec
