### ISSUE TITLE
Allow lookups with just middle mouse button

### ISSUE THREAD

**Issue by forsakeninfinity** [rampaa/JL#59]
Some games will always move forward on left click / touch even outside of the text area which makes that mode untenable for lookups. 

Lookup with mouse move + Middle mouse button to mine is fine and seems to be the expected default but it feels far too intrusive to me, with random audio bits playing as you just move the mouse. 

It would be very nice to just be able to lookup with Middle mouse button as an option too instead of just the left click / touch (and I would like for it to continue to launch straight into mining mode).

**Comment by rampaa** [comment]
> it feels far too intrusive to me, with random audio bits playing as you just move the mouse

That shouldn't happen unless you enabled the "Auto play audio" setting.

**Comment by forsakeninfinity** [comment]
Indeed. That being the case, I do want the audio to autoplay on lookup. I just don't want to spam the lookup I guess. Another reason I prefer the other modes that jump you into mining mode is being able to scroll down the definitions right away. It would be nice to have it directly on MMB too for the games that move ahead on left click anywhere. Much appreciate the quick responses 🙇

**Comment by forsakeninfinity** [comment]
Oh and please also allow clicking with MMB on the word to mine it, to address the same problem with the game going forward on left clicks🙇
