### ISSUE TITLE
Weird behaviour of pop-up window with scaling turned on.

### ISSUE THREAD

**Issue by yourmom2002** [rampaa/JL#6]
So i have 1440p display with 110% custom scaling turned on (same thing happens with 125% scaling btw). 
Not sure how to describe it, but pop-up window ignores offset settings and sometimes even appears outside of screen and flickers. 
Everything fine if i set scaling back to 100%. 
Video
https://user-images.githubusercontent.com/99648105/156923944-74fd31da-fd17-4c04-b31c-a013d3a1707d.mp4

Settings
 ![JL_06 19-41-06 Preferences](https://user-images.githubusercontent.com/99648105/156923939-74c12ca1-2c17-4ef8-803d-84fc1908c615.png)

**Comment by yourmom2002** [comment]
Updated to 1.3. Pop-up window won't go beyond screen anymore, but flickering still happens it's too close to screen border. Also pop-up window position is still off, compared to whenever i run JL with 100% scaling.

**Comment by rampaa** [comment]
Thanks for the detailed explanation and testing. Should be fixed in version 1.4.

**Comment by yourmom2002** [comment]
Thanks, after update to 1.4, it works like a charm. 
Pretty much switch to JL completely at this point, really love it so far.

One more thing, not gonna create separate issue just yet, cause i can't replicate this one. Normally vn window stays focused whenever i look something up in JL, but when bug(?) occurs, vn window losing focus every time i look something in JL (i.e. when pop-up window appears). Causing some vns to stop playing sound (and for some of them you can't even change this behaviour in settings). 
Happened few times in 1.3, will do more testing later if issue appears later / if i can point out way to replicate this.

**Comment by mertvn** [comment]
> One more thing, not gonna create separate issue just yet, cause i can't replicate this one. Normally vn window stays focused whenever i look something up in JL, but when bug(?) occurs, vn window losing focus every time i look something in JL (i.e. when pop-up window appears). Causing some vns to stop playing sound (and for some of them you can't even change this behaviour in settings). Happened few times in 1.3, will do more testing later if issue appears later / if i can point out way to replicate this. (probably not related to scaling/dpi even)

Added an option in 1.5 to disable focusing on lookup.
