### ISSUE TITLE
Opacity on unhover not working after the first hover

### ISSUE THREAD

**Issue by Mansive** [rampaa/JL#60]
The setting works when JL is first launched, but if I hover over the window and then unhover, the opacity does not change back and longer changes for subsequent unhovers. This issue seems to go away if Lookup mode is set to Mouse move instead of either Mouse click/Touch or Text select.

**Comment by rampaa** [comment]
Fixed by https://github.com/rampaa/JL/commit/82f75e8dc7fa40e591cea66a1bd1f80b9d0b9ba0. The fix will be included in the next release.
