### ISSUE TITLE
Touchscreen device optimisations

### ISSUE THREAD

**Issue by Rik-Kirtaniya** [rampaa/JL#64]
I have recently started using JL on a touchscreen windows laptop, and while it works pretty amazingly out of the box, I would like to suggest a few optimizations that it could have to make the experience seamless.

1. Adding a couple of arrow buttons on the main window to access the backlog and navigate it, since scrolling with touchscreen gestures doesn't exactly seem possible in there. Probably a couple of up and down arrows on the left/right side or maybe a left arrow and a right arrow on either side of the window respectively.

2. This might be slightly more complicated to implement, but making it possible to navigate the dictionary popup. For now, it seems like touching the popup just makes it close, even when focus on lookup is selected in the popup settings. Maybe making it so that touching the popup doesn't close it, plus having a couple of arrows to navigate it in the same way as above. This is just a suggestion, maybe some other approach to this would be more feasible.

3. This should be simpler, preventing JL from triggering the touch keyboard. Whenever I touch JL's main window with my laptop being in tablet mode (where it makes the touch keyboard pop up when focused on text boxes), it thinks that it is a text box and causes the touch keyboard to pop up incessantly for every touch. This happens even when the main window is set to read only in its settings.

That's pretty much all I can think of for now. Would be glad if you consider these worth implementing. Thank you for your time!

**Comment by rampaa** [comment]
> Adding a couple of arrow buttons on the main window to access the backlog and navigate it, since scrolling with touchscreen gestures doesn't exactly seem possible in there.

This does make sense but I want main window to remain as minimalistic as possible. I will try and see if I can implement something like swipe gesture when I have the time. There's a chance that I may cave in and add some buttons for backlog navigation but no promises.

> it seems like touching the popup just makes it close

This shouldn't happen. Make sure that you are using the "Mouse click/Touch" lookup mode and not "Mouse move".

> This happens even when the main window is set to read only in its settings.

This is a WPF bug, see https://github.com/dotnet/wpf/issues/1133. I did some quick Googling and found out how to disable this behavior permanently (e.g., https://stackoverflow.com/a/41744743) but ideally when the textbox is not read only, the virtual keyboard should still pop up. I will try and see whether I can make it work like that when I have the time.
