### ISSUE TITLE
Feature Request: Addition Of Profiles

### ISSUE THREAD

**Issue by alythesniper** [rampaa/JL#66]
It would be very helpful to have a feature that lets you save the current text size, window size, window position, visible on hover, opacity of hover, etc. instead of having to change all of them manually every time you go to a different game

**Comment by rampaa** [comment]
I think Anki/Dictionary/Frequency/Audio Source settings probably shouldn't be a part of a profile, i.e., those settings should be shared between all profiles. Stats and everything else under the preferences probably should be profile specific though. What do you think? Do you have any strong preference as to what should and shouldn't be a profile specific setting? If you do have a strong preference please do tell your reasoning for it.

I do think I will implement this feature eventually but in the meantime you can manually simulate it yourself. All your preferences (apart from the settings for Anki/Dictionary/Frequency/Audio Source/Stats) are stored in JL.dll.config. So after fine-tuning your preferences for a game you can keep a copy of it like JL.dll_tsukihime.config, JL.dll_aikotoba.config etc. and when you you want to use a specific config you've created before just change its name to JL.dll.config and run JL afterwards.

**Comment by alythesniper** [comment]
I think that separation for what goes into profiles and what doesn't sounds good. The only thing I would say I have a strong preference on is basically the entire "Main Window" section, almost everything there is stuff that I have changed between games to make the text overlay as close to what a "in game dictionary" experience would probably be, from font to size, painstaking positioning, etc. The rest I personally have not changed between games, but maybe some people want different popup settings to fit the game colours or something? I don't believe there would be any harm in leaving that in. 

Something else that I do just want to mention as a potential feature in the future, it would be very useful to have a process that "auto detects" settings based on a screenshot of a game to try and guess parameters like font, positioning, font size, line spacing, etc. to overlay as best as possible - I do think this would probably take a lot of effort and not worth it in the mean time, but just wanted to mention it in case a time where such a feature would be worthwhile does come. Thanks a lot for JL, your continued development, and the info on the manual profiles - I will certainly use it till profiles come officially.

**Comment by rampaa** [comment]
> I will implement this feature eventually

Done. You can find the profile settings under Preferences->Advanced.

All preferences (save for Anki/Dictionary/Frequency/Audio Source settings) are profile specific now.

You can also add profile specific custom names/words as well. Selecting "Custom Name/Word Dictionary (Profile)" in the "add name/word" window will add the name/word for the current profile, selecting "Custom Name/Word Dictionary" will add it to a profile-independent dictionary.
