### ISSUE TITLE
the text box overlay is not showing up on steam link

### ISSUE THREAD

**Issue by JunkyardCat** [rampaa/JL#67]
so im using steam link to play my game and the text box isnt showing up but on pc i can see the overlay fine(i checked this while steam link is running).
im playing dangan ronpa 1 on steam

**Comment by rampaa** [comment]
I don't use Steam Link but downloaded it just to see if I can reproduce your issue and it just worked fine. Make sure that:

1) You are running Steam as administrator (if you gave JL [UI Access](https://github.com/rampaa/JL/blob/master/UI%20Access.md), you NEED administrator privilege to interact with JL)

2) Maybe disable the "Text only visible on hover" and "Change opacity on unhover" settings (it works fine on my end even when those settings are enabled but I guess it's something you can try)

If none of those works maybe give [Sunshine](https://github.com/LizardByte/Sunshine)+[Moonlight](https://moonlight-stream.org/) a go, I know some people use that setup to use JL.

Either way, it's not a JL bug or anything, so closing the issue.

**Comment by rampaa** [comment]
Okay, managed to reproduce the problem. It only happens when you start a game through Steam. It seems like Steam Link simulates fullscreen for games in your Steam library and it discards all other windows that does not have focus. You can enable General->Focusable (and maybe Main Window->Focus on unhover) and JL window will show up when you move the cursor to position where JL is placed.

**Comment by JunkyardCat** [comment]
@rampaa 


> Okay, managed to reproduce the problem. It only happens when you start a game through Steam. It seems like Steam Link simulates fullscreen for games in your Steam library and it discards all other windows that does not have focus. You can enable "General->Focusable" (and maybe "Main Window->Focus on hover" as well) and JL window will show up when you move the cursor to a position where JL is placed.

i tried this but steam always changes the control layout . so sometimes im able to get it to show and its control layout changes to the desktop layout but as soon i tap the game again it changes back to builtin controller layout. i tried starting it outside the steam game library but it still has the same issue

**Comment by rampaa** [comment]
> so sometimes im able to get it to show and its control layout changes to the desktop layout but as soon i tap the game again it changes back to builtin controller layout.

Yes, once you tab the game itself, Steam Links will simulate a fake fullscreen once again and JL will be become invisible again. The idea is if you don't frequently do lookups, you could make JL visible only when you need it.

> i tried starting it outside the steam game library but it still has the same issue

Try running a game not found in your Steam library. I tried running a few games not found in my Steam library and they worked fine whether I used their built-in fullscreen functionality or created a fake fullscreen with Magpie. This obviously won't solve your problem for games found in your Steam library.

Honestly, there's not much I can do. I could theoretically add an option that makes JL keep the focus all the time, then I guess JL window would appear without you clicking on a position where it's placed, but then you probably wouldn't be able to properly interact with the game itself. I'd give [Sunshine](https://github.com/LizardByte/Sunshine)+[Moonlight](https://moonlight-stream.org/) a go if I were you.

**Comment by JunkyardCat** [comment]
@rampaa 
i tried sunshine and moonlight and it works great but lacks a few feature on moonlight. zoom and virtual keyboard or just keys overlay 

thanks man
