### ISSUE TITLE
Pitch Accent to Anki

### ISSUE THREAD

**Issue by NeonGooRoo** [rampaa/JL#72]
Am I missing something or is there no way to insert pitch accent into anki cards? Would be a very nice feature, the only thing that I miss from Yomichan

**Comment by rampaa** [comment]
What would you expect a possible Pitch Accent field to return for the following entry?

![image](https://github.com/rampaa/JL/assets/25622653/0ed81c42-8f09-4635-890b-335840f89fca)

a) [3], [0], [1]
b) おんな: [3], おみな: [0], おうな: [1]
c) おんなꜜ, おみな, おꜜうな
d) LHHꜜ, LHH, HꜜLL
e) おんな: LHHꜜ, おみな: LHH, おうな: HꜜLL
f) Some sort of SVG?
g) Something else entirely?

**Comment by rampaa** [comment]
Done. The new `Pitch Accent` field creates an HTML like the following:
![image](https://github.com/rampaa/JL/assets/25622653/62bfb967-f50e-4545-b174-6a03593e3536)

**Comment by NeonGooRoo** [comment]
you are king
