### ISSUE TITLE
Is there a reading + definition option for anki?

### ISSUE THREAD

**Issue by Nils55** [rampaa/JL#77]
I'm trying to mine with anki connect but I usually make my cards with kanji on the front and hiragana reading + definition on the back. Is that possible? Seems I can only choose one or the other.

**Comment by rampaa** [comment]
Are you perhaps using the "Basic" note type/model? You need to create custom note types for JL (ideally one for words/others, one for kanjis and one for names). Those note types should preferably have all the JL fields for that expression type. e.g., `Primary Spelling`, `Readings`, `Alternative Spellings`, `Definitions` etc. for the note type created for `Word`s. `Primary Spelling`, `Kun Readings`, `On Readings` etc. for the note type created for `Kanji`s and so on. You can choose which of these fields will be shown on the back/front side of your cards. See https://docs.ankiweb.net/editing.html#adding-a-note-type and https://docs.ankiweb.net/templates/intro.html for more details.

When you create a note type with the necessary fields, you must select that note type as your "model" and after that you can simply pair the corresponding JL fields with the card fields, like the following:

![image](https://github.com/rampaa/JL/assets/25622653/e2a461e0-fd38-4ecb-8f74-cdf4f7c99a66)
