### ISSUE TITLE
Text captured throught agent websocket add unwanted informations

### ISSUE THREAD

**Issue by YashaNoos** [rampaa/JL#93]
Hello!
I'm trying to setup JL to work with AI The somnium files (steam version) using text hooked with [agent](https://github.com/0xDC00/agent)
And everything works except that every time JL main window display  a new line it adds annoying unwanted informations about what I guess is agent's internal processes.
=>
![AI_TheSomniumFilestest](https://github.com/user-attachments/assets/465249bd-a005-4e5d-aaa5-b40fda27105d)

I tried a text hooking page (renji) and the text shows up perfectly
=>
<img width="391" alt="Renji" src="https://github.com/user-attachments/assets/2544239e-e478-47b3-b848-6f2ec6aa131b">

I tried to play around with JL and agent settings but wasn't able to find a solution.
Have a nice day a thanks for the hard work!

**Comment by rampaa** [comment]
It seems like either Agent is using [KamWithK/TextractorSender](https://github.com/KamWithK/TextractorSender) or mimicking its behavior to work with [KamWithK/exSTATic](https://github.com/KamWithK/exSTATic).

It seems like [Renji-XD/Texthooker UI](https://github.com/Renji-XD/texthooker-ui) is special casing that format but I don't want JL to special case any custom formats like that. For Textractor there are extensions that send the game text without any unneeded info like [Mansive/TextractorSender](https://github.com/Mansive/TextractorSender) and [sadolit/textractor-websocket](https://github.com/sadolit/textractor-websocket). You should ask [0xDC00/agent](https://github.com/0xDC00/agent) to add an option to send only the game text without all that fluff as JL will not special case it.

I may add an RegEx filtering/replacement feature to JL in the future which would allow you to filter/replace arbitrary text but no promises.

**Comment by YashaNoos** [comment]
I will ask agent for a solution, thanks for your reply!

**Comment by rampaa** [comment]
I didn't try it out on my end to see if it really works but you can the following change in `...agent\data\libWebSocket.js` to make Agent send only the raw game text:

Change
```JS
function broadcast(e) {
    const message = JSON.stringify({
        process_path: e.detail.target,
        id: e.detail.id,
        sentence: e.detail.text,
        type: e.type
    });

    wss.clients.forEach(function (client) {
        if (client.readyState === WebSocket.OPEN) {
            client.send(message);
        }
    });
```

to
```JS
function broadcast(e) {
    wss.clients.forEach(function (client) {
        if (client.readyState === WebSocket.OPEN) {
            client.send(e.detail.text);
        }
    });
```

Again, I didn't try it out on my end, so I don't know if it will work. If you happen to try it out, let me know whether it works for you or not.

**Comment by YashaNoos** [comment]
I just made the change to libWebSocket.js mine was located here=> `...agent-v0.1.4-win32-x64\data\scripts\libWebSocket.js` 
And it works perfectly!
![AI_TheSomniumFiles_DsXCqgtBvs](https://github.com/user-attachments/assets/04dd98eb-36ab-4fdd-956f-83704d74bcec)

Thanks a lot for your dedication! I'm gonna update the issue on agent's page with your work around, have a nice day!
