### ISSUE TITLE
Lookups for english words can't find matches when words start with capital letters

### ISSUE THREAD

**Issue by Roeekush** [rampaa/JL#95]
Hello

I'm trying to set up JL English for a friend.

When JL is looking through an english dictionary, it seems as if capital letters mess it up

Yomitan handles capital letters fine using the same dictionary.

I captured a video to explain this issue better:

https://github.com/user-attachments/assets/873e78fe-ca03-4fd4-80a0-d61b9f494095

I uploaded the English to Japanese dictionary I was using: [Vicon_Eng_to_Jp_Dictionary.zip](https://github.com/user-attachments/files/16322235/Vicon_Eng_to_Jp_Dictionary.zip)

**Comment by rampaa** [comment]
JL is intended exclusively for "Japanese -> Any Language" lookups, not for "Any Language -> Any Language" lookups.

Although it is trivial to fix the specific problem you are facing, it's out of JL's scope. For proper lookup support for English, JL would need to find the dictionary form of words (e.g. went -> go), which is, again, out of this project's scope.

**Comment by rampaa** [comment]
If you can think of a specific case where this would help for "Japanese->Any Language" lookups, I'd be willing to fix this issue.

Something like https://en.wikipedia.org/wiki/List_of_Japanese_Latin_alphabetic_abbreviations comes to mind. But I can't remember ever seeing, for example, "NG" as "ng". If you can think of a Japanese abbreviation in Latin alphabet that is used both in its lower-case and upper-case form for the same meaning, feel free to let me know.
